### ISSUE TITLE
期望npl能实现AES/DES常用加密算法

### ISSUE THREAD

**Issue by Darren1414** [NPLPackages/main#91]

**Comment by LiXizhi** [comment]
![image](https://user-images.githubusercontent.com/94537/38812125-f9f92a94-41bd-11e8-94e8-ba134ec049c4.png)

It has a basic rsa support, but not very fast. only used in hash generation.  True encryption library takes up many lines of code.  One may consider using a C++ library.

**Comment by xixichen007** [comment]
DES和RSA算法能否也加上？
