### ISSUE TITLE
del key not working in the first line of mcml2 multiline editbox

### ISSUE THREAD

**Issue by LiXizhi** [NPLPackages/main#98]
![image](https://user-images.githubusercontent.com/94537/40585007-d494d510-61dd-11e8-87b8-9052fd25fda7.png)

`del` key not working in the first line and first characterof mcml2 multiline editbox. 
It works in other positions.

**Comment by LiXizhi** [comment]
@lipengg

**Comment by lipengg** [comment]
fixed

**Comment by lipengg** [comment]
this bug is fixed.
now it will delete the next character when you hit del key in the first line and first character.
